### ISSUE TITLE
I can not press [ Bake Animation Clip ] button

### ISSUE THREAD

**Issue by nick-burge** [Unity-Technologies/facial-ar-remote#16]
hi

faical ar remote Is wonderful.

so I want to save an animation clip About the [StreamReader] Using the [Bake Animation Clip] button.

but The [Bake Animation Clip] button does not become active and can not be changed to animation clip.

If you know something about how to use this, please let me know.

thank you.

**Comment by kkarannn** [comment]
Select the animation clip first from the tab above the bake animation button outside play mode.

**Comment by kkarannn** [comment]
Also, you need to record some animation first, of course.

**Comment by mtschoen-unity** [comment]
Hi there @nick-burge. It looks like you may have found a "feature not a bug" type issue. The button is disabled until you have an recording selected, and the recording list is empty until you make your first recording. We had considered including a test recording with the package, but ultimately decided this would be confusing, since the whole point is to use your phone to record your own performances.

I hope this has helped to explain the issue you were having. If it hasn't, or if you are still unable to record a performance and bake an animation, please re-open the issue and provide further information.
