### ISSUE TITLE
Scripting Define Symbols*   ARKIT_2_0 

### ISSUE THREAD

**Issue by spartancc** [Unity-Technologies/facial-ar-remote#2]
![1](https://user-images.githubusercontent.com/42367711/44073702-c457863e-9fc7-11e8-9ece-74df91c25724.png)
Hello, I want to ask what is wrong with this error?

**Comment by SometimesSean** [comment]
Hey, just spotted a couple of steps that are missed on the build settings docs.

1. import TMP Essential Resources for TextMesh Pro
2. Enable "ARKit Uses Facetracking" on UnityARKitPlugin > Resources > UnityARKitPlugIn > ARKitSettings

I wasn't familiar with either, so spent a bit of time working this out. Hopefully save some others the headache. Otherwise, great work guys, I'm going to get a lot of use out of this.

**Comment by jonathan-unity** [comment]
If you are wanting to use ARKit 2 features you will need to be using the latest version of the ARKit plugin from our bitbucket repo found here https://bitbucket.org/Unity-Technologies/unity-arkit-plugin
Also note that you will need to build from the beta version of XCode and have iOS 12 beta on your device.

**Comment by mtschoen-unity** [comment]
I just checked the latest version of Facial AR Remote in Unity 2018.1 with ARKIT_2_0 in the Scripting Define Symbols and do not see this error. I believe this has been fixed. Feel free to reopen the issue if you still see it after updating to the latest version.
