### ISSUE TITLE
Is it possible to use this tool outside a local network?

### ISSUE THREAD

**Issue by Pier-P-Guillen** [Unity-Technologies/facial-ar-remote#48]
Hi,

First of all, thanks for the tool!

I'm working on a project where we would like to use the face data from ARKit to animate some characters on the PC, in real-time. I've been testing it locally with this tool, and so far, so good. 
We'd like to also animate using data from iPhones that would be outside of the network the PC is in. Is this possible?

I'm assuming it might be outside the scope of this tool but, any help on how to achieve this would be appreciated. :)

**Comment by mtschoen-unity** [comment]
Hi there! In principle, what you are talking about is possible, but you are right to say that it is out of scope for the tool. We use a regular C# socket to make the connection between the PC and the phone, so as long as you are able to make that connection you can transfer the data. The issue comes down to the fact that most people don't have their PC hooked up to the internet directly, so you need to set up [port forwarding](https://en.wikipedia.org/wiki/Port_forwarding) on your router and it's hard to ensure that it will work reliably for everyone and provide support when it doesn't.

Many internet service providers also block you from listening on any port, which makes it a non-starter. To do this "properly" over the internet you would want a relay server, similar to how Multiplay, Photon and other networking solutions provide multiplayer services for games.
